[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src fonts.gstatic.com; object-src 'none'"
    X-Frame-Options = "DENY"