[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src fonts.gstatic.com; object-src 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"